### ISSUE TITLE
Auto install the script in opt

### ISSUE THREAD

**Issue by Mte90** [TheZ3ro/penmode3#4]
Is better that in post installation a symbolic link in /usr/local/bin or /opt for a fast installation

**Comment by TheZ3ro** [comment]
It's already setted by the "bin" parameter in the package.json ;)

**Comment by Mte90** [comment]
so the readme is not updated?

**Comment by TheZ3ro** [comment]
Why?

**Comment by Mte90** [comment]
My fault I don't have see that that instruction was for the git installation.

**Comment by b4dtR1p** [comment]
Hahaha TVB mte

**Comment by TheZ3ro** [comment]
Also the "npm link" create the link in PATH so for now we are ok
